apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: keda
  namespace: argocd
spec:
  destination:
    namespace: keda
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize/keda/overlays/docker-desktop/lld/
    repoURL: https://github.com/Tusharvasshistha/argo-cd.git
    targetRevision: refs/heads/main
  syncPolicy:
    syncOptions:
    - FailOnSharedResource=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
