apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system-components-kustomize
  namespace: argocd
spec:
  generators:
  - git:
      directories:
      - path: kustomize/*/*/overlays/docker-desktop
      repoURL: https://github.com/Tusharvasshistha/argo-cd.git
      revision: refs/heads/main
  template:
    metadata:
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      name: '{{path[2]}}.syscomp'
      namespace: argocd
    spec:
      destination:
        namespace: '{{path[1]}}'
        server: https://kubernetes.default.svc
      project: system
      source:
        path: '{{path}}'
        repoURL: https://github.com/Tusharvasshistha/argo-cd.git
        targetRevision: refs/heads/main
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - FailOnSharedResource=true
        - ApplyOutOfSyncOnly=true
