apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: keda
  namespace: argocd
spec:
  destination:
    namespace: keda
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - jsonPointers:
    - /metadata/labels/app.kubernetes.io~1instance
    kind: Service
  - group: admissionregistration.k8s.io
    jsonPointers:
    - /metadata/labels/app.kubernetes.io~1instance
    kind: ValidatingWebhookConfiguration
    name: keda-admission
  project: default
  source:
    path: kustomize/keda/overlays/docker-desktop
    repoURL: https://github.com/Tusharvasshistha/argo-cd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - FailOnSharedResource=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
    - CreateNamespace=true
