apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: Application
    name: Keda-install
    namespace: argocd
  patch: |
    - op: replace
      path: /spec/source/path
      value: kustomize/keda/overlays/docker-desktop
