apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: ApplicationSet
    name: system-components-kustomize
    namespace: argocd
  patch: |
    - op: replace
      path: /spec/generators/0/git/directories/0/path
      value: 'kustomize/*/*/overlays/docker-desktop'
