apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Tusharvasshistha/argo-cd.git
    path: <PATH>
    targetRevision: refs/heads/main
  destination:
    namespace: keda
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - FailOnSharedResource=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
